l2chains = [{name = "OP Mainnet", chainId = 10}] # e.g. [{name = "OP Mainnet", chainId = 10}]

templateName = "EnableDeputyPauseModuleTemplate"

newModule = "TBD"
[addresses]
FoundationOperationSafe = "0x9BA6e03D8B90dE867373Db8cF1A58d2F7F006b3A"
